<?php


/**
 * Implementation of hook_form_alter()
 */
function hosting_http_basic_auth_ldap_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {

    $form['http_basic_auth_ldap'] = array(
      '#type' => 'fieldset',
      '#title' => t('HTTP Basic LDAP Authentication'),
      '#description' => t('Specify an LDAP server and Require to authenticate against ldap.'),
    );

    $form['http_basic_auth_ldap']['http_basic_auth_ldap_server'] = array(
      '#type' => 'textfield',
      '#title' => t('Server'),
      '#default_value' => $form['#node']->http_basic_auth_ldap_server ? $form['#node']->http_basic_auth_ldap_server : '',
      '#weight' => 0,
    );
    $form['http_basic_auth_ldap']['http_basic_auth_ldap_require'] = array(
      '#type' => 'textfield',
      '#title' => t('Require'),
      '#default_value' => $form['#node']->http_basic_auth_ldap_require ? $form['#node']->http_basic_auth_ldap_require : '',
      '#weight' => 1,
    );
    $form['http_basic_auth_ldap']['http_basic_auth_ldap_message'] = array(
      '#type' => 'textfield',
      '#title' => t('Message'),
      '#default_value' => $form['#node']->http_basic_auth_ldap_message ? $form['#node']->http_basic_auth_ldap_message : t('Restricted access'),
      '#weight' => 2,
    );
    return $form;
  }
}

/**
 * Implementation of hook_insert()
 */
function hosting_http_basic_auth_ldap_insert($node) {
  if ($node->http_basic_auth_ldap_server) {
    db_query("INSERT INTO {hosting_http_basic_auth_ldap} (vid, nid, server, require, message) VALUES (%d, %d, '%s', '%s', '%s')", $node->vid, $node->nid, $node->http_basic_auth_ldap_server, $node->http_basic_auth_ldap_require, $node->http_basic_auth_ldap_message);
  }
}

/**
 * Implementation of hook_update()
 */
function hosting_http_basic_auth_ldap_update($node) {
  if (FALSE === db_fetch_array(db_query("SELECT server AS http_basic_auth_ldap_server, require AS http_basic_auth_ldap_require FROM {hosting_http_basic_auth_ldap} WHERE vid = %d", $node->vid))) {
    hosting_http_basic_auth_ldap_insert($node);
  }
  else {
    db_query("UPDATE {hosting_http_basic_auth_ldap} SET server = '%s', require = '%s', message ='%s' WHERE vid = %d", $node->http_basic_auth_ldap_server, $node->http_basic_auth_ldap_require, $node->http_basic_auth_ldap_message, $node->vid);
  }

}

/**
 * Implementation of hook_delete()
 */
function hosting_http_basic_auth_ldap_delete($node) {
  db_query("DELETE FROM {hosting_http_basic_auth_ldap} WHERE nid=%d", $node->nid);
}

/**
 * Implementation of hook_delete_revision()
 */
function hosting_http_basic_auth_ldap_delete_revision($node) {
  db_query("DELETE FROM {hosting_http_basic_auth_ldap} WHERE vid=%d", $node->vid);
}

/**
 * Implementation of hook_nodeapi()
 */
function hosting_http_basic_auth_ldap_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
    case 'insert':
        hosting_http_basic_auth_ldap_insert($node);
        break;
      case 'update':
        hosting_http_basic_auth_ldap_update($node);
        break;
      case 'delete' :
        hosting_http_basic_auth_ldap_delete($node);
        break;
      case 'delete revision':
        hosting_http_basic_auth_ldap_delete_revision($node);
        break;
      case 'validate' :
        if (!empty($node->http_basic_auth_ldap_server) && empty($node->http_basic_auth_ldap_require)) {
          form_set_error('http_basic_auth_ldap_require', t('You must specify a server and require for the HTTP basic Ldap authentication.'));
        }
        break;
      case 'load':
        $additions = db_fetch_array(db_query("SELECT server AS http_basic_auth_ldap_server, require AS http_basic_auth_ldap_require, message AS http_basic_auth_ldap_message FROM {hosting_http_basic_auth_ldap} WHERE vid = %d", $node->vid));
        return $additions;
        break;
    }
  }
}

/**
* Implementation of hook_feeds_node_processor_targets_alter().
*/
function hosting_http_basic_auth_ldap_feeds_node_processor_targets_alter(&$targets, $content_type) {
  if ($content_type == 'site') {
    $targets['http_basic_auth_ldap_server'] = array(
      'name' => t('HTTP Basic Auth - server'),
      'description' => t('Set this to somethining like - ldap://ldap.some.de/ou=users,dc=some,dc=de?uid.'),
      'callback' => 'hosting_http_basic_auth_ldap_set_target_http_basic_auth_ldap_simple',
    );

    $targets['http_basic_auth_ldap_require'] = array(
      'name' => t('HTTP Basic Auth - require'),
      'description' => t('An apache Require stanza like - ldap-filter &(objectClass=inetOrgPerson)(objectClass=tracUser)'),
      'callback' => 'hosting_http_basic_auth_ldap_set_target_http_basic_auth_ldap_simple',
    );

    $targets['http_basic_auth_ldap_message'] = array(
      'name' => t('HTTP Basic Auth - username'),
      'description' => t('A message to show when prompting the user for username and password.'),
      'callback' => 'hosting_http_basic_auth_ldap_set_target_http_basic_auth_ldap_message',
    );

  }
}

/**
 * Mapping callback for feeds.
 */
function hosting_http_basic_auth_ldap_set_target_http_basic_auth_ldap_simple($node, $target, $value) {
  if (!empty($value)) {
    $node->$target = $value;
  }
}

/**
 * Mapping callback for feeds.
 */
function hosting_http_basic_auth_ldap_set_target_http_basic_auth_ldap_message($node, $target, $value) {
  $node->$target = !empty($value) ? $value : t('Restricted access');
}
